layout_spectrum: 0.3182131
typography_spectrum: 0.8328654
color:
  saturation: 0.4014505
  lightness: 0.7734213
  brandStrength: 0.635352
  rhythmicContrast: 0.6522642
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Cityboybushcraft
